name: tests/studio

on:
  push:
    branches:
        - feature/*
        - release/**
        - 'v[4-9]+.[0-9]+'

  pull_request:
    branches:
        - feature/*
        - release/**
        - 'v[4-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Install dependencies
      run: dotnet restore

    - name: Build dotnet
      run: dotnet build

    - name: Install npm dependencies
      run: npm install
      working-directory: ./src/Raven.Studio
  
    - name: Restore Studio
      run: npm run restore
      working-directory: ./src/Raven.Studio

    - name: Compile Studio
      run: npm run compile
      working-directory: ./src/Raven.Studio

    - name: Test Studio
      run: npm run test
      working-directory: ./src/Raven.Studio
